
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/about' #change it according to your repository name



# Profile information
yourname: Phat Hong  ## put your name
title: 'Front-end Web Developer'  ## your title
location: District 11, HCMC, Viet Nam


## Social Profiles
facebook: http://www.facebook.com/hpphat  ## your facebook account url
twitter: http://www.twitter.com/hpphat92  ## your twitter account url
linkedin: https://www.linkedin.com/in/hpphat1992/  ## your linkedin account url
github: https://github.com/hpphat92  ## you github account url
wordpress: http://hpphat.wordpress.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
